# Generated by Django 5.2.6 on 2026-09-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabric',
            options={'ordering': ['fabric_name']},
        ),
        migrations.AlterField(
            model_name='fabric',
            name='composition',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='construction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='fabric_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='fiber',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='fiber_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='structure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='weight',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
