# Generated by Django 6.1 on 2026-10-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0002_alter_fabric_options_alter_fabric_composition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='weight',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
