# Generated by Django 6.1 on 2026-10-03 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alter_measurement_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('in', 'Inches'), ('kg', 'Kilograms'), ('lb', 'Pounds')], max_length=2),
        ),
        migrations.AlterField(
            model_name='measurementtype',
            name='unit',
            field=models.CharField(choices=[('cm', 'Centimeters'), ('in', 'Inches'), ('kg', 'Kilograms'), ('lb', 'Pounds')], default='cm', max_length=2),
        ),
        migrations.CreateModel(
            name='StandardMeasurementRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_requirements', to='measurements.measurementtype')),
            ],
            options={
                'ordering': ['standard_set__gender', 'standard_set__context', 'measurement_type__category', 'measurement_type__name'],
            },
        ),
        migrations.CreateModel(
            name='StandardMeasurementSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('context', models.CharField(choices=[('casual', 'Casual'), ('corporate', 'Corporate')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('measurement_types', models.ManyToManyField(related_name='standard_sets', through='measurements.StandardMeasurementRequirement', to='measurements.measurementtype')),
            ],
            options={
                'ordering': ['gender', 'context'],
            },
        ),
        migrations.AddField(
            model_name='standardmeasurementrequirement',
            name='standard_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='measurements.standardmeasurementset'),
        ),
        migrations.AddConstraint(
            model_name='standardmeasurementset',
            constraint=models.UniqueConstraint(fields=('gender', 'context'), name='uniq_standard_measurement_gender_context'),
        ),
        migrations.AddConstraint(
            model_name='standardmeasurementrequirement',
            constraint=models.UniqueConstraint(fields=('standard_set', 'measurement_type'), name='uniq_standard_set_measurement_type'),
        ),
    ]
